# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  # TODO [romeira]: Add support for 2.x python versions {04/12/17 09:29}
  # - 2.7
  # - 2.6

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox


